### PR TITLE
created requirements folder

### PR DESCRIPTION
**Pull request by sage-godspeed**
as per request on slack

### CODE REVIEW

**Comment by mykeels** [comment]
I can only see a single empty line in the commit. Am I missing something?

**Comment by sage-godspeed** [comment]
am sorry bout that i have rectified it

**Comment by mykeels** [comment]
I think you be making a pull-request of https://github.com/sage-godspeed/college-portal/tree/markdown to this master branch, rather than for https://github.com/sage-godspeed/college-portal/tree/patch-2, which has only one empty commit.

Do you want to close this pull-request and create another from your `markdown` branch into this `master` branch?

**Comment by mykeels** [comment]
Oh, I just saw you'd created another pull-request 😄  ... I'm closing this now!

**Pull request closed without merging**
